version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      AUTOCOMPLETE_SYSTEM_DATABASE_USERNAME: postgres
      AUTOCOMPLETE_SYSTEM_DATABASE_PASSWORD: postgres
      AUTOCOMPLETE_SYSTEM_DATABASE_HOST: db
      AUTOCOMPLETE_SYSTEM_CACHE_HOST: 127.0.0.1
      AUTOCOMPLETE_SYSTEM_CACHE_PORT: 6379
      AUTOCOMPLETE_SYSTEM_CACHE_DB: 1
      AUTOCOMPLETE_SYSTEM_DOCUMENT_DATABASE_HOST: mongo
      AUTOCOMPLETE_SYSTEM_DOCUMENT_DATABASE_PORT: 27017
    depends_on:
      - db
      - cache
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
volumes:
  db_data:
    driver: local
  mongo_data:
    driver: local